(define (problem crate-push-problem)
    (:domain deliveroo-crates)
    (:objects
        ag crate_target t_0_0 t_0_1 t_0_2 t_1_0 t_1_1 t_1_2
    )
    (:init
        (crate-move-capable t_0_0)
        (clear t_0_0)
        (right t_0_0 t_1_0)
        (left t_1_0 t_0_0)
        (up t_0_0 t_0_1)
        (down t_0_1 t_0_0)
        (crate-move-capable t_0_1)
        (right t_0_1 t_1_1)
        (left t_1_1 t_0_1)
        (up t_0_1 t_0_2)
        (down t_0_2 t_0_1)
        (crate-move-capable t_0_2)
        (clear t_0_2)
        (right t_0_2 t_1_2)
        (left t_1_2 t_0_2)
        (crate-move-capable t_1_0)
        (clear t_1_0)
        (up t_1_0 t_1_1)
        (down t_1_1 t_1_0)
        (crate-move-capable t_1_1)
        (clear t_1_1)
        (up t_1_1 t_1_2)
        (down t_1_2 t_1_1)
        (crate-move-capable t_1_2)
        (clear t_1_2)
        (me ag)
        (at ag t_0_0)
        (at crate_target t_0_1)
    )
    (:goal (at crate_target t_0_2))
)